#!/bin/bash
cd /home/zahara/SaharaAnalytics/zd_tools
./reporter /var/log/nginx/analytics.access.log-20100801.gz 100 > /home/zahara/public_html/reports/analytics-summary-20100729.html
./reporter /var/log/nginx/analytics.access.log-20100802.gz 100 > /home/zahara/public_html/reports/analytics-summary-20100801.html
./reporter /var/log/nginx/analytics.access.log-20100803.gz 100 > /home/zahara/public_html/reports/analytics-summary-20100802.html
./reporter /var/log/nginx/analytics.access.log-20100804.gz 100 > /home/zahara/public_html/reports/analytics-summary-20100803.html
./reporter /var/log/nginx/analytics.access.log-20100805.gz 100 > /home/zahara/public_html/reports/analytics-summary-20100804.html
./reporter /var/log/nginx/analytics.access.log-20100806.gz 100 > /home/zahara/public_html/reports/analytics-summary-20100805.html
./reporter /var/log/nginx/analytics.access.log-20100807.gz 100 > /home/zahara/public_html/reports/analytics-summary-20100806.html
./reporter /var/log/nginx/analytics.access.log-20100808.gz 100 > /home/zahara/public_html/reports/analytics-summary-20100807.html
./reporter /var/log/nginx/analytics.access.log-20100809.gz 100 > /home/zahara/public_html/reports/analytics-summary-20100808.html
./reporter /var/log/nginx/analytics.access.log-20100810.gz 100 > /home/zahara/public_html/reports/analytics-summary-20100809.html
./reporter /var/log/nginx/analytics.access.log-20100811.gz 100 > /home/zahara/public_html/reports/analytics-summary-20100810.html
./reporter /var/log/nginx/analytics.access.log-20100812.gz 100 > /home/zahara/public_html/reports/analytics-summary-20100811.html
